In [49]:
import numpy as np
import pandas as pd

In [50]:
df = pd.read_csv('https://gist.githubusercontent.com/DiogoRibeiro7/c6590d0cf119e87c39e31c21a9c0f3a8/raw/4a8e3da267a0c1f0d650901d8295a5153bde8b21/PlayTennis.csv')

In [51]:
df

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [52]:
pd.crosstab(df['Outlook'],df['Play Tennis'])

Play Tennis  No  Yes
Outlook
Overcast      0    4
Rain          2    3
Sunny         3    2

In [53]:
pd.crosstab(df['Outlook'],df['Play Tennis'],normalize='columns') # Joint probability

Play Tennis   No       Yes
Outlook
Overcast     0.0  0.444444
Rain         0.4  0.333333
Sunny        0.6  0.222222

In [54]:
pd.crosstab(df['Outlook'],df['Play Tennis'],normalize='columns').stack() # transforming data series to 1d

Outlook   Play Tennis
Overcast  No             0.000000
          Yes            0.444444
Rain      No             0.400000
          Yes            0.333333
Sunny     No             0.600000
          Yes            0.222222
dtype: float64

In [55]:
pd.crosstab(df['Outlook'],df['Play Tennis'],normalize='columns').stack().to_dict()

{('Overcast', 'No'): 0.0,
 ('Overcast', 'Yes'): 0.4444444444444444,
 ('Rain', 'No'): 0.4,
 ('Rain', 'Yes'): 0.3333333333333333,
 ('Sunny', 'No'): 0.6,
 ('Sunny', 'Yes'): 0.2222222222222222}

In [56]:
D={}

for i in ['Outlook','Temperature','Humidity','Wind']:
    D.update(pd.crosstab(df[i],df['Play Tennis'],normalize='columns').stack().to_dict())

In [57]:
D

{('Overcast', 'No'): 0.0,
 ('Overcast', 'Yes'): 0.4444444444444444,
 ('Rain', 'No'): 0.4,
 ('Rain', 'Yes'): 0.3333333333333333,
 ('Sunny', 'No'): 0.6,
 ('Sunny', 'Yes'): 0.2222222222222222,
 ('Cool', 'No'): 0.2,
 ('Cool', 'Yes'): 0.3333333333333333,
 ('Hot', 'No'): 0.4,
 ('Hot', 'Yes'): 0.2222222222222222,
 ('Mild', 'No'): 0.4,
 ('Mild', 'Yes'): 0.4444444444444444,
 ('High', 'No'): 0.8,
 ('High', 'Yes'): 0.3333333333333333,
 ('Normal', 'No'): 0.2,
 ('Normal', 'Yes'): 0.6666666666666666,
 ('Strong', 'No'): 0.6,
 ('Strong', 'Yes'): 0.3333333333333333,
 ('Weak', 'No'): 0.4,
 ('Weak', 'Yes'): 0.6666666666666666}

# Sentiment Analysis

In [58]:
import kagglehub
import pandas as pd

# Download dataset
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

# Load manually
df = pd.read_csv(f"{path}/IMDB Dataset.csv", encoding='latin1')

df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [59]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text Cleaning

1. Sample 10000 rows
2. Remove html tags
3. Remove special characters
4. Converting every thing to lower case
5. Removing Stop words
6. Stemming

In [60]:
df=df.sample(10000)

In [61]:
df.shape

(10000, 2)

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 49563 to 20022
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [63]:
# target column encoded
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_15884\1823462540.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_15884\1823462540.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [64]:
df.head()

                                                  review  sentiment
49563  The great cinematic musicals were made between...          1
8419   Second-feature concerns a young woman in Londo...          1
33274  From the first to the last scene, this film is...          1
11744  Do you know when you look at your collection o...          0
22032  "Two Hands" is a good addition to the Australi...          1

# Data Cleaning

In [65]:
import re
clean=re.compile('<.*?>')
re.sub(clean,'',df.iloc[2].review)

'From the first to the last scene, this film is made very realistically,even too realistically that sometimes we can\'t see details in night scenes(it\'s dark as real night),in the desert(sunshine is so strong as in real desert). Script and actor\'s play are also very realistic. Shots and episodes are edited not to show things and events "effectively", to "explain" them, or,as many Hollywood films do, to "entertain" viewers. Editing here is to represent the events as if they really happened in Afganistan. Camera is set sometimes far from dying solders, even the moment when the main character Major Bandura is shot and killed.Such method reminds me of masterpieces of Italian neo-realism. And the construction of the story here is based on the same principles as "PaisÃ\xa0",or "The Bicycle Thief"--chronological series of "true to life" episodes and a few pathetic moments, which at first seem to be sudden and illogical, but have inner reasons.I think the inner reason of Major Bandura\'s suicidal death is religious emotion--Repentance for innocent people\'s death(not only his accidental killing of family in the village, but also death of solders under his command).He is not depicted as a eager believer,on the contrary he is depicted as tactful and responsible officer.Exactly for this reason his last decisions(to go back to the destroyed village and to turn his back to an armed boy, whose family he killed)seem an act of Repentance. The Russian Orthodox choral, which sounds at the end("Evening Sacrifice")is another context,by which all the film can be seen from this point of view.'

# function to clean html tags

In [66]:
def clean_html(text):
    clean=re.compile('<.*?>')
    return re.sub(clean,'',text)

In [67]:
df['review']=df['review'].apply(clean_html)

In [68]:
df['review'][9]

'If you like original gut wrenching laughter you will like this movie. If you are young or old then you will love this movie, hell even my mom liked it.Great Camp!!!'

# converting everything to lower

In [69]:
def convert_lower(text):
    return text.lower()

In [70]:
df['review']=df['review'].apply(convert_lower)

In [71]:
df['review'][9]

'if you like original gut wrenching laughter you will like this movie. if you are young or old then you will love this movie, hell even my mom liked it.great camp!!!'

# function to remove special characters

In [72]:
def remove_Special(text):
    x=''

    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+' '
    return x

In [73]:
remove_Special(' th%e @ classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare. forget pretty pictures painted for mainstream audiences, f')

' th e   classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare  forget pretty pictures painted for mainstream audiences  f'

In [74]:
df['review']=df['review'].apply(remove_Special)

# Remove the stop words

In [75]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [76]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [77]:
df

                                                  review  sentiment
49563  the great cinematic musicals were made between...          1
8419   second feature concerns a young woman in londo...          1
33274  from the first to the last scene  this film is...          1
11744  do you know when you look at your collection o...          0
22032   two hands  is a good addition to the australi...          1
...                                                  ...        ...
22711  the other boleyn girl   not to be confused wit...          0
49019  not very impressed  its difficult to offer any...          0
30285  i somehow failed for a few years to see this f...          0
45948  this is a great documentary film  any fan of c...          1
20022  i saw the korean version of daisy first  it ca...          1

[10000 rows x 2 columns]

In [78]:
def remove_stopwords(text):
    x=[]
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [ ]:
df['review']=df['review'].apply(remove_stopwords)

# Perform stemming

In [ ]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
y=[]
def stem_words