# Plotly Basics

In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.offline as pyo

matches=pd.read_csv(r"E:\data\matplotlib_data\matches.csv")
deliveries=pd.read_csv("E:\data\matplotlib_data\deliveries.csv")

In [2]:
ipl=deliveries.merge(matches,left_on='match_id',right_on='id')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

In [6]:
ipl.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'season', 'city', 'date',
       'match_type', 'player_of_match', 'venue', 'team1', 'team2',
       'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin',
       'target_runs', 'target_overs', 'super_over', 'method', 'umpire1',
       'umpire2'],
      dtype='object')

# Scatter Plot

In [ ]:
# top50 batters

In [3]:
top50=ipl.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(50).index.tolist()
new_ipl=ipl[ipl['batter'].isin(top50)]
new_ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

In [4]:
# calculating SR
# sr=(sum_score/sum_ball)*100
runs=new_ipl.groupby('batter')['batsman_runs'].sum()
balls=new_ipl.groupby('batter')['batsman_runs'].count()

sr=(runs/balls)*100
sr=sr.reset_index()
sr

            batter  batsman_runs
0   AB de Villiers    148.580442
1       AD Russell    164.224422
2         AJ Finch    123.349057
3        AM Rahane    120.321410
4        AT Rayudu    124.584527
5      BB McCullum    126.848592
6         CH Gayle    142.121729
7        DA Miller    134.684477
8        DA Warner    135.429986
9         DR Smith    132.279534
10    F du Plessis    133.071325
11       G Gambhir    119.665153
12      GJ Maxwell    150.488599
13       HH Pandya    139.691290
14    Ishan Kishan    132.797589
15      JC Buttler    142.238984
16       JH Kallis    105.936272
17      KA Pollard    140.457703
18      KD Karthik    131.353404
19        KL Rahul    131.050866
20   KS Williamson    122.952710
21         M Vijay    118.614130
22      MA Agarwal    128.255646
23       MK Pandey    117.366180
24        MS Dhoni    132.835065
25          N Rana    130.818859
26        PA Patel    116.625717
27       Q de Kock    131.120332
28        R Dravid    113.347237
29       RA Jadeja    124.432296
30     RA Tripathi    135.515152
31      RD Gaikwad    133.632791
32       RG Sharma    127.918194
33         RR Pant    143.597561
34      RV Uthappa    126.152279
35        S Dhawan    123.454313
36        SA Yadav    142.505948
37        SE Marsh    130.109775
38        SK Raina    132.535312
39       SPD Smith    124.812406
40    SR Tendulkar    114.187867
41       SR Watson    134.163209
42         SS Iyer    123.025540
43       SV Samson    135.137615
44    Shubman Gill    132.236842
45         V Kohli    128.511867
46        V Sehwag    148.827059
47         WP Saha    123.902027
48       YK Pathan    138.046272
49    Yuvraj Singh    124.784776

In [5]:
# calculating avg
# avg=sum_runs/sum_outs
out=ipl[ipl['player_dismissed'].isin(top50)]
nout=out['player_dismissed'].value_counts()

avg=runs/nout
avg=avg.reset_index()
avg.rename(columns={'index':'batter',0:'avg'},inplace=True)
avg=avg.merge(sr,on='batter')
avg

            batter        avg  batsman_runs
0   AB de Villiers  39.853846    148.580442
1       AD Russell  28.930233    164.224422
2         AJ Finch  24.904762    123.349057
3        AM Rahane  30.142857    120.321410
4        AT Rayudu  28.051613    124.584527
5      BB McCullum  27.711538    126.848592
6         CH Gayle  39.658730    142.121729
7        DA Miller  35.658537    134.684477
8        DA Warner  40.042683    135.429986
9         DR Smith  28.392857    132.279534
10    F du Plessis  35.992126    133.071325
11       G Gambhir  31.007353    119.665153
12      GJ Maxwell  24.750000    150.488599
13       HH Pandya  28.471910    139.691290
14    Ishan Kishan  28.430108    132.797589
15      JC Buttler  37.715789    142.238984
16       JH Kallis  28.552941    105.936272
17      KA Pollard  28.404959    140.457703
18      KD Karthik  26.320652    131.353404
19        KL Rahul  44.657143    131.050866
20   KS Williamson  35.533333    122.952710
21         M Vijay  25.930693    118.614130
22      MA Agarwal  22.811966    128.255646
23       MK Pandey  29.015038    117.366180
24        MS Dhoni  39.126866    132.835065
25          N Rana  28.344086    130.818859
26        PA Patel  22.603175    116.625717
27       Q de Kock  30.980392    131.120332
28        R Dravid  28.233766    113.347237
29       RA Jadeja  27.398148    124.432296
30     RA Tripathi  26.939759    135.515152
31      RD Gaikwad  41.754386    133.632791
32       RG Sharma  29.730942    127.918194
33         RR Pant  35.451613    143.597561
34      RV Uthappa  27.522222    126.152279
35        S Dhawan  35.072539    123.454313
36        SA Yadav  31.805310    142.505948
37        SE Marsh  39.507937    130.109775
38        SK Raina  32.374269    132.535312
39       SPD Smith  34.652778    124.812406
40    SR Tendulkar  33.826087    114.187867
41       SR Watson  30.793651    134.163209
42         SS Iyer  31.948980    123.025540
43       SV Samson  30.687500    135.137615
44    Shubman Gill  37.835294    132.236842
45         V Kohli  38.714976    128.511867
46        V Sehwag  27.555556    148.827059
47         WP Saha  24.247934    123.902027
48       YK Pathan  29.290909    138.046272
49    Yuvraj Singh  24.810811    124.784776

In [40]:
# scatter plot
trace=go.Scatter(x=avg['avg'],y=avg['batsman_runs'],mode='markers',
                 text=avg['batter'],marker={'color':'#00a65a','size':16})
data=[trace]
layout=go.Layout(title='Batsman Abg vs Sr',
                xaxis={'title':'Batsman Average'},
                yaxis={'title':'Batsman strike rate'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig,filename='ram.html')

'ram.html'

In [6]:
# year by year batsman performance
single=ipl[ipl['batter']=='V Kohli']
performance=single.groupby('season')['batsman_runs'].sum().reset_index()
performance

     season  batsman_runs
0   2007/08           165
1      2009           246
2   2009/10           307
3      2011           557
4      2012           364
5      2013           639
6      2014           359
7      2015           505
8      2016           973
9      2017           308
10     2018           530
11     2019           464
12  2020/21           471
13     2021           405
14     2022           341
15     2023           639
16     2024           741

# Line Plot

In [46]:
trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],
                mode='lines',marker={'color':'#00a66a'})
data=[trace]
layout=go.Layout(title='year by year performance',
                xaxis={'title':'season'},
                yaxis={'title':'total runs'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [7]:
# multiple line plot
# year by year batsman performance
single1=ipl[ipl['batter']=='RG Sharma']
performance1=single1.groupby('season')['batsman_runs'].sum().reset_index()
performance1

     season  batsman_runs
0   2007/08           404
1      2009           362
2   2009/10           404
3      2011           372
4      2012           433
5      2013           538
6      2014           390
7      2015           482
8      2016           489
9      2017           333
10     2018           286
11     2019           405
12  2020/21           334
13     2021           381
14     2022           268
15     2023           332
16     2024           417

In [49]:
trace1=go.Scatter(x=performance1['season'],y=performance1['batsman_runs'],
                mode='lines',marker={'color':'#00a66a'},name='RG Sharma')
trace2=go.Scatter(x=performance['season'],y=performance['batsman_runs'],
                mode='lines',name='V Kohli')
data=[trace1,trace2]
layout=go.Layout(title='year by year performance',
                xaxis={'title':'season'},
                yaxis={'title':'total runs'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [8]:
def batsman_comp(*name):
    data=[]
    for i in name:
        single=ipl[ipl['batter']==i]
        performance=single.groupby('season')['batsman_runs'].sum().reset_index()

        trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],
                        mode='lines + markers',name=i)
        data.append(trace)

        layout=go.Layout(title='Batsman Record comparision',
                        xaxis={'title':'season'},
                        yaxis={'title':'Runs'})
        fig=go.Figure(data=data,layout=layout)
        pyo.plot(fig)

In [52]:
batsman_comp('V Kohli','RG Sharma','MS Dhoni','G Gambhir')

In [9]:
# top 10 batsman
top10=ipl.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(10).index.tolist()
top10_df=ipl[ipl['batter'].isin(top10)]


top10_scores=top10_df.groupby('batter')['batsman_runs'].sum().reset_index()
top10_scores

           batter  batsman_runs
0  AB de Villiers          5181
1        CH Gayle          4997
2       DA Warner          6567
3      KD Karthik          4843
4        MS Dhoni          5243
5       RG Sharma          6630
6      RV Uthappa          4954
7        S Dhawan          6769
8        SK Raina          5536
9         V Kohli          8014

In [68]:
trace=go.Bar(x=top10_scores['batter'],y=top10_scores['batsman_runs'])
data=[trace]
layout=go.Layout(title='Top Runs Scorer in Ipl',
                xaxis={'title':'batsman name'},
                yaxis={'title':'runs'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [11]:
wins_by_team = (
    matches["winner"]
    .value_counts()
    .reset_index()
    .rename(columns={"index": "team", "winner": "wins"})
    .head(10)
)

In [12]:
wins_by_team

                          wins  count
0               Mumbai Indians    144
1          Chennai Super Kings    138
2        Kolkata Knight Riders    131
3  Royal Challengers Bangalore    116
4             Rajasthan Royals    112
5              Kings XI Punjab     88
6          Sunrisers Hyderabad     88
7             Delhi Daredevils     67
8               Delhi Capitals     48
9              Deccan Chargers     29

In [26]:
trace=go.Bar(x=wins_by_team['wins'],y=wins_by_team['count'],marker=dict(color='royalblue'))
data=[trace]

layout=go.Layout(title='Most Winnings Teams',
                xaxis={'title':'team Names'},
                yaxis={'title':'Winning Counts'})

fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

ValueError: Invalid property specified for object of type plotly.graph_objs.Bar: 'mode'

Did you mean "base"?

    Valid properties:
        alignmentgroup
            Set several traces linked to the same position axis or
            matching axes to the same alignmentgroup. This controls
            whether bars compute their positional range dependently
            or independently.
        base
            Sets where the bar base is drawn (in position axis
            units). In "stack" or "relative" barmode, traces that
            set "base" will be excluded and drawn in "overlay" mode
            instead.
        basesrc
            Sets the source reference on Chart Studio Cloud for
            `base`.
        cliponaxis
            Determines whether the text nodes are clipped about the
            subplot axes. To show the text nodes above axis lines
            and tick labels, make sure to set `xaxis.layer` and
            `yaxis.layer` to *below traces*.
        constraintext
            Constrain the size of text inside or outside a bar to
            be no larger than the bar itself.
        customdata
            Assigns extra data each datum. This may be useful when
            listening to hover, click and selection events. Note
            that, "scatter" traces also appends customdata items in
            the markers DOM elements
        customdatasrc
            Sets the source reference on Chart Studio Cloud for
            `customdata`.
        dx
            Sets the x coordinate step. See `x0` for more info.
        dy
            Sets the y coordinate step. See `y0` for more info.
        error_x
            :class:`plotly.graph_objects.bar.ErrorX` instance or
            dict with compatible properties
        error_y
            :class:`plotly.graph_objects.bar.ErrorY` instance or
            dict with compatible properties
        hoverinfo
            Determines which trace information appear on hover. If
            `none` or `skip` are set, no information is displayed
            upon hovering. But, if `none` is set, click and hover
            events are still fired.
        hoverinfosrc
            Sets the source reference on Chart Studio Cloud for
            `hoverinfo`.
        hoverlabel
            :class:`plotly.graph_objects.bar.Hoverlabel` instance
            or dict with compatible properties
        hovertemplate
            Template string used for rendering the information that
            appear on hover box. Note that this will override
            `hoverinfo`. Variables are inserted using %{variable},
            for example "y: %{y}" as well as %{xother}, {%_xother},
            {%_xother_}, {%xother_}. When showing info for several
            points, "xother" will be added to those with different
            x positions from the first point. An underscore before
            or after "(x|y)other" will add a space on that side,
            only when this field is shown. Numbers are formatted
            using d3-format's syntax %{variable:d3-format}, for
            example "Price: %{y:$.2f}".
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format
            for details on the formatting syntax. Dates are
            formatted using d3-time-format's syntax
            %{variable|d3-time-format}, for example "Day:
            %{2019-01-01|%A}". https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format for details on the
            date formatting syntax. The variables available in
            `hovertemplate` are the ones emitted as event data
            described at this link
            https://plotly.com/javascript/plotlyjs-events/#event-
            data. Additionally, every attributes that can be
            specified per-point (the ones that are `arrayOk: true`)
            are available. Finally, the template string has access
            to variables `value` and `label`. Anything contained in
            tag `<extra>` is displayed in the secondary box, for
            example `<extra>%{fullData.name}</extra>`. To hide the
            secondary box completely, use an empty tag
            `<extra></extra>`.
        hovertemplatesrc
            Sets the source reference on Chart Studio Cloud for
            `hovertemplate`.
        hovertext
            Sets hover text elements associated with each (x,y)
            pair. If a single string, the same string appears over
            all the data points. If an array of string, the items
            are mapped in order to the this trace's (x,y)
            coordinates. To be seen, trace `hoverinfo` must contain
            a "text" flag.
        hovertextsrc
            Sets the source reference on Chart Studio Cloud for
            `hovertext`.
        ids
            Assigns id labels to each datum. These ids for object
            constancy of data points during animation. Should be an
            array of strings, not numbers or any other type.
        idssrc
            Sets the source reference on Chart Studio Cloud for
            `ids`.
        insidetextanchor
            Determines if texts are kept at center or start/end
            points in `textposition` "inside" mode.
        insidetextfont
            Sets the font used for `text` lying inside the bar.
        legend
            Sets the reference to a legend to show this trace in.
            References to these legends are "legend", "legend2",
            "legend3", etc. Settings for these legends are set in
            the layout, under `layout.legend`, `layout.legend2`,
            etc.
        legendgroup
            Sets the legend group for this trace. Traces and shapes
            part of the same legend group hide/show at the same
            time when toggling legend items.
        legendgrouptitle
            :class:`plotly.graph_objects.bar.Legendgrouptitle`
            instance or dict with compatible properties
        legendrank
            Sets the legend rank for this trace. Items and groups
            with smaller ranks are presented on top/left side while
            with "reversed" `legend.traceorder` they are on
            bottom/right side. The default legendrank is 1000, so
            that you can use ranks less than 1000 to place certain
            items before all unranked items, and ranks greater than
            1000 to go after all unranked items. When having
            unranked or equal rank items shapes would be displayed
            after traces i.e. according to their order in data and
            layout.
        legendwidth
            Sets the width (in px or fraction) of the legend for
            this trace.
        marker
            :class:`plotly.graph_objects.bar.Marker` instance or
            dict with compatible properties
        meta
            Assigns extra meta information associated with this
            trace that can be used in various text attributes.
            Attributes such as trace `name`, graph, axis and
            colorbar `title.text`, annotation `text`
            `rangeselector`, `updatemenues` and `sliders` `label`
            text all support `meta`. To access the trace `meta`
            values in an attribute in the same trace, simply use
            `%{meta[i]}` where `i` is the index or key of the
            `meta` item in question. To access trace `meta` in
            layout attributes, use `%{data[n[.meta[i]}` where `i`
            is the index or key of the `meta` and `n` is the trace
            index.
        metasrc
            Sets the source reference on Chart Studio Cloud for
            `meta`.
        name
            Sets the trace name. The trace name appears as the
            legend item and on hover.
        offset
            Shifts the position where the bar is drawn (in position
            axis units). In "group" barmode, traces that set
            "offset" will be excluded and drawn in "overlay" mode
            instead.
        offsetgroup
            Set several traces linked to the same position axis or
            matching axes to the same offsetgroup where bars of the
            same position coordinate will line up.
        offsetsrc
            Sets the source reference on Chart Studio Cloud for
            `offset`.
        opacity
            Sets the opacity of the trace.
        orientation
            Sets the orientation of the bars. With "v" ("h"), the
            value of the each bar spans along the vertical
            (horizontal).
        outsidetextfont
            Sets the font used for `text` lying outside the bar.
        selected
            :class:`plotly.graph_objects.bar.Selected` instance or
            dict with compatible properties
        selectedpoints
            Array containing integer indices of selected points.
            Has an effect only for traces that support selections.
            Note that an empty array means an empty selection where
            the `unselected` are turned on for all points, whereas,
            any other non-array values means no selection all where
            the `selected` and `unselected` styles have no effect.
        showlegend
            Determines whether or not an item corresponding to this
            trace is shown in the legend.
        stream
            :class:`plotly.graph_objects.bar.Stream` instance or
            dict with compatible properties
        text
            Sets text elements associated with each (x,y) pair. If
            a single string, the same string appears over all the
            data points. If an array of string, the items are
            mapped in order to the this trace's (x,y) coordinates.
            If trace `hoverinfo` contains a "text" flag and
            "hovertext" is not set, these elements will be seen in
            the hover labels.
        textangle
            Sets the angle of the tick labels with respect to the
            bar. For example, a `tickangle` of -90 draws the tick
            labels vertically. With "auto" the texts may
            automatically be rotated to fit with the maximum size
            in bars.
        textfont
            Sets the font used for `text`.
        textposition
            Specifies the location of the `text`. "inside"
            positions `text` inside, next to the bar end (rotated
            and scaled if needed). "outside" positions `text`
            outside, next to the bar end (scaled if needed), unless
            there is another bar stacked on this one, then the text
            gets pushed inside. "auto" tries to position `text`
            inside the bar, but if the bar is too small and no bar
            is stacked on this one the text is moved outside. If
            "none", no text appears.
        textpositionsrc
            Sets the source reference on Chart Studio Cloud for
            `textposition`.
        textsrc
            Sets the source reference on Chart Studio Cloud for
            `text`.
        texttemplate
            Template string used for rendering the information text
            that appear on points. Note that this will override
            `textinfo`. Variables are inserted using %{variable},
            for example "y: %{y}". Numbers are formatted using
            d3-format's syntax %{variable:d3-format}, for example
            "Price: %{y:$.2f}".
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format
            for details on the formatting syntax. Dates are
            formatted using d3-time-format's syntax
            %{variable|d3-time-format}, for example "Day:
            %{2019-01-01|%A}". https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format for details on the
            date formatting syntax. Every attributes that can be
            specified per-point (the ones that are `arrayOk: true`)
            are available. Finally, the template string has access
            to variables `value` and `label`.
        texttemplatesrc
            Sets the source reference on Chart Studio Cloud for
            `texttemplate`.
        uid
            Assign an id to this trace, Use this to provide object
            constancy between traces during animations and
            transitions.
        uirevision
            Controls persistence of some user-driven changes to the
            trace: `constraintrange` in `parcoords` traces, as well
            as some `editable: true` modifications such as `name`
            and `colorbar.title`. Defaults to `layout.uirevision`.
            Note that other user-driven trace attribute changes are
            controlled by `layout` attributes: `trace.visible` is
            controlled by `layout.legend.uirevision`,
            `selectedpoints` is controlled by
            `layout.selectionrevision`, and `colorbar.(x|y)`
            (accessible with `config: {editable: true}`) is
            controlled by `layout.editrevision`. Trace changes are
            tracked by `uid`, which only falls back on trace index
            if no `uid` is provided. So if your app can add/remove
            traces before the end of the `data` array, such that
            the same trace has a different index, you can still
            preserve user-driven changes if you give each trace a
            `uid` that stays with it as it moves.
        unselected
            :class:`plotly.graph_objects.bar.Unselected` instance
            or dict with compatible properties
        visible
            Determines whether or not this trace is visible. If
            "legendonly", the trace is not drawn, but can appear as
            a legend item (provided that the legend itself is
            visible).
        width
            Sets the bar width (in position axis units).
        widthsrc
            Sets the source reference on Chart Studio Cloud for
            `width`.
        x
            Sets the x coordinates.
        x0
            Alternate to `x`. Builds a linear space of x
            coordinates. Use with `dx` where `x0` is the starting
            coordinate and `dx` the step.
        xaxis
            Sets a reference between this trace's x coordinates and
            a 2D cartesian x axis. If "x" (the default value), the
            x coordinates refer to `layout.xaxis`. If "x2", the x
            coordinates refer to `layout.xaxis2`, and so on.
        xcalendar
            Sets the calendar system to use with `x` date data.
        xhoverformat
            Sets the hover text formatting rulefor `x`  using d3
            formatting mini-languages which are very similar to
            those in Python. For numbers, see:
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format.
            And for dates see: https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format. We add two items to
            d3's date formatter: "%h" for half of the year as a
            decimal number as well as "%{n}f" for fractional
            seconds with n digits. For example, *2016-10-13
            09:15:23.456* with tickformat "%H~%M~%S.%2f" would
            display *09~15~23.46*By default the values are
            formatted using `xaxis.hoverformat`.
        xperiod
            Only relevant when the axis `type` is "date". Sets the
            period positioning in milliseconds or "M<n>" on the x
            axis. Special values in the form of "M<n>" could be
            used to declare the number of months. In this case `n`
            must be a positive integer.
        xperiod0
            Only relevant when the axis `type` is "date". Sets the
            base for period positioning in milliseconds or date
            string on the x0 axis. When `x0period` is round number
            of weeks, the `x0period0` by default would be on a
            Sunday i.e. 2000-01-02, otherwise it would be at
            2000-01-01.
        xperiodalignment
            Only relevant when the axis `type` is "date". Sets the
            alignment of data points on the x axis.
        xsrc
            Sets the source reference on Chart Studio Cloud for
            `x`.
        y
            Sets the y coordinates.
        y0
            Alternate to `y`. Builds a linear space of y
            coordinates. Use with `dy` where `y0` is the starting
            coordinate and `dy` the step.
        yaxis
            Sets a reference between this trace's y coordinates and
            a 2D cartesian y axis. If "y" (the default value), the
            y coordinates refer to `layout.yaxis`. If "y2", the y
            coordinates refer to `layout.yaxis2`, and so on.
        ycalendar
            Sets the calendar system to use with `y` date data.
        yhoverformat
            Sets the hover text formatting rulefor `y`  using d3
            formatting mini-languages which are very similar to
            those in Python. For numbers, see:
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format.
            And for dates see: https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format. We add two items to
            d3's date formatter: "%h" for half of the year as a
            decimal number as well as "%{n}f" for fractional
            seconds with n digits. For example, *2016-10-13
            09:15:23.456* with tickformat "%H~%M~%S.%2f" would
            display *09~15~23.46*By default the values are
            formatted using `yaxis.hoverformat`.
        yperiod
            Only relevant when the axis `type` is "date". Sets the
            period positioning in milliseconds or "M<n>" on the y
            axis. Special values in the form of "M<n>" could be
            used to declare the number of months. In this case `n`
            must be a positive integer.
        yperiod0
            Only relevant when the axis `type` is "date". Sets the
            base for period positioning in milliseconds or date
            string on the y0 axis. When `y0period` is round number
            of weeks, the `y0period0` by default would be on a
            Sunday i.e. 2000-01-02, otherwise it would be at
            2000-01-01.
        yperiodalignment
            Only relevant when the axis `type` is "date". Sets the
            alignment of data points on the y axis.
        ysrc
            Sets the source reference on Chart Studio Cloud for
            `y`.
        zorder
            Sets the layer on which this trace is displayed,
            relative to other SVG traces on the same subplot. SVG
            traces with higher `zorder` appear in front of those
            with lower `zorder`.

Did you mean "base"?

Bad property path:
mode
^^^^

In [16]:
matches.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [23]:
ipl.shape

(260920, 37)