# Plotly Basics

In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.offline as pyo

matches=pd.read_csv(r"E:\data\matplotlib_data\matches.csv")
deliveries=pd.read_csv("E:\data\matplotlib_data\deliveries.csv")

In [2]:
ipl=deliveries.merge(matches,left_on='match_id',right_on='id')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

In [6]:
ipl.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'season', 'city', 'date',
       'match_type', 'player_of_match', 'venue', 'team1', 'team2',
       'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin',
       'target_runs', 'target_overs', 'super_over', 'method', 'umpire1',
       'umpire2'],
      dtype='object')

# Scatter Plot

In [ ]:
# top50 batters

In [3]:
top50=ipl.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(50).index.tolist()
new_ipl=ipl[ipl['batter'].isin(top50)]
new_ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

In [4]:
# calculating SR
# sr=(sum_score/sum_ball)*100
runs=new_ipl.groupby('batter')['batsman_runs'].sum()
balls=new_ipl.groupby('batter')['batsman_runs'].count()

sr=(runs/balls)*100
sr=sr.reset_index()
sr

            batter  batsman_runs
0   AB de Villiers    148.580442
1       AD Russell    164.224422
2         AJ Finch    123.349057
3        AM Rahane    120.321410
4        AT Rayudu    124.584527
5      BB McCullum    126.848592
6         CH Gayle    142.121729
7        DA Miller    134.684477
8        DA Warner    135.429986
9         DR Smith    132.279534
10    F du Plessis    133.071325
11       G Gambhir    119.665153
12      GJ Maxwell    150.488599
13       HH Pandya    139.691290
14    Ishan Kishan    132.797589
15      JC Buttler    142.238984
16       JH Kallis    105.936272
17      KA Pollard    140.457703
18      KD Karthik    131.353404
19        KL Rahul    131.050866
20   KS Williamson    122.952710
21         M Vijay    118.614130
22      MA Agarwal    128.255646
23       MK Pandey    117.366180
24        MS Dhoni    132.835065
25          N Rana    130.818859
26        PA Patel    116.625717
27       Q de Kock    131.120332
28        R Dravid    113.347237
29       RA Jadeja    124.432296
30     RA Tripathi    135.515152
31      RD Gaikwad    133.632791
32       RG Sharma    127.918194
33         RR Pant    143.597561
34      RV Uthappa    126.152279
35        S Dhawan    123.454313
36        SA Yadav    142.505948
37        SE Marsh    130.109775
38        SK Raina    132.535312
39       SPD Smith    124.812406
40    SR Tendulkar    114.187867
41       SR Watson    134.163209
42         SS Iyer    123.025540
43       SV Samson    135.137615
44    Shubman Gill    132.236842
45         V Kohli    128.511867
46        V Sehwag    148.827059
47         WP Saha    123.902027
48       YK Pathan    138.046272
49    Yuvraj Singh    124.784776

In [5]:
# calculating avg
# avg=sum_runs/sum_outs
out=ipl[ipl['player_dismissed'].isin(top50)]
nout=out['player_dismissed'].value_counts()

avg=runs/nout
avg=avg.reset_index()
avg.rename(columns={'index':'batter',0:'avg'},inplace=True)
avg=avg.merge(sr,on='batter')
avg

            batter        avg  batsman_runs
0   AB de Villiers  39.853846    148.580442
1       AD Russell  28.930233    164.224422
2         AJ Finch  24.904762    123.349057
3        AM Rahane  30.142857    120.321410
4        AT Rayudu  28.051613    124.584527
5      BB McCullum  27.711538    126.848592
6         CH Gayle  39.658730    142.121729
7        DA Miller  35.658537    134.684477
8        DA Warner  40.042683    135.429986
9         DR Smith  28.392857    132.279534
10    F du Plessis  35.992126    133.071325
11       G Gambhir  31.007353    119.665153
12      GJ Maxwell  24.750000    150.488599
13       HH Pandya  28.471910    139.691290
14    Ishan Kishan  28.430108    132.797589
15      JC Buttler  37.715789    142.238984
16       JH Kallis  28.552941    105.936272
17      KA Pollard  28.404959    140.457703
18      KD Karthik  26.320652    131.353404
19        KL Rahul  44.657143    131.050866
20   KS Williamson  35.533333    122.952710
21         M Vijay  25.930693    118.614130
22      MA Agarwal  22.811966    128.255646
23       MK Pandey  29.015038    117.366180
24        MS Dhoni  39.126866    132.835065
25          N Rana  28.344086    130.818859
26        PA Patel  22.603175    116.625717
27       Q de Kock  30.980392    131.120332
28        R Dravid  28.233766    113.347237
29       RA Jadeja  27.398148    124.432296
30     RA Tripathi  26.939759    135.515152
31      RD Gaikwad  41.754386    133.632791
32       RG Sharma  29.730942    127.918194
33         RR Pant  35.451613    143.597561
34      RV Uthappa  27.522222    126.152279
35        S Dhawan  35.072539    123.454313
36        SA Yadav  31.805310    142.505948
37        SE Marsh  39.507937    130.109775
38        SK Raina  32.374269    132.535312
39       SPD Smith  34.652778    124.812406
40    SR Tendulkar  33.826087    114.187867
41       SR Watson  30.793651    134.163209
42         SS Iyer  31.948980    123.025540
43       SV Samson  30.687500    135.137615
44    Shubman Gill  37.835294    132.236842
45         V Kohli  38.714976    128.511867
46        V Sehwag  27.555556    148.827059
47         WP Saha  24.247934    123.902027
48       YK Pathan  29.290909    138.046272
49    Yuvraj Singh  24.810811    124.784776

In [40]:
# scatter plot
trace=go.Scatter(x=avg['avg'],y=avg['batsman_runs'],mode='markers',
                 text=avg['batter'],marker={'color':'#00a65a','size':16})
data=[trace]
layout=go.Layout(title='Batsman Abg vs Sr',
                xaxis={'title':'Batsman Average'},
                yaxis={'title':'Batsman strike rate'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig,filename='ram.html')

'ram.html'

In [6]:
# year by year batsman performance
single=ipl[ipl['batter']=='V Kohli']
performance=single.groupby('season')['batsman_runs'].sum().reset_index()
performance

     season  batsman_runs
0   2007/08           165
1      2009           246
2   2009/10           307
3      2011           557
4      2012           364
5      2013           639
6      2014           359
7      2015           505
8      2016           973
9      2017           308
10     2018           530
11     2019           464
12  2020/21           471
13     2021           405
14     2022           341
15     2023           639
16     2024           741

# Line Plot

In [46]:
trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],
                mode='lines',marker={'color':'#00a66a'})
data=[trace]
layout=go.Layout(title='year by year performance',
                xaxis={'title':'season'},
                yaxis={'title':'total runs'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [7]:
# multiple line plot
# year by year batsman performance
single1=ipl[ipl['batter']=='RG Sharma']
performance1=single1.groupby('season')['batsman_runs'].sum().reset_index()
performance1

     season  batsman_runs
0   2007/08           404
1      2009           362
2   2009/10           404
3      2011           372
4      2012           433
5      2013           538
6      2014           390
7      2015           482
8      2016           489
9      2017           333
10     2018           286
11     2019           405
12  2020/21           334
13     2021           381
14     2022           268
15     2023           332
16     2024           417

In [49]:
trace1=go.Scatter(x=performance1['season'],y=performance1['batsman_runs'],
                mode='lines',marker={'color':'#00a66a'},name='RG Sharma')
trace2=go.Scatter(x=performance['season'],y=performance['batsman_runs'],
                mode='lines',name='V Kohli')
data=[trace1,trace2]
layout=go.Layout(title='year by year performance',
                xaxis={'title':'season'},
                yaxis={'title':'total runs'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [8]:
def batsman_comp(*name):
    data=[]
    for i in name:
        single=ipl[ipl['batter']==i]
        performance=single.groupby('season')['batsman_runs'].sum().reset_index()

        trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],
                        mode='lines + markers',name=i)
        data.append(trace)

        layout=go.Layout(title='Batsman Record comparision',
                        xaxis={'title':'season'},
                        yaxis={'title':'Runs'})
        fig=go.Figure(data=data,layout=layout)
        pyo.plot(fig)

In [52]:
batsman_comp('V Kohli','RG Sharma','MS Dhoni','G Gambhir')

In [8]:
# top 10 batsman
top10=ipl.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(10).index.tolist()
top10_df=ipl[ipl['batter'].isin(top10)]


top10_scores=top10_df.groupby('batter')['batsman_runs'].sum().reset_index()
top10_scores

           batter  batsman_runs
0  AB de Villiers          5181
1        CH Gayle          4997
2       DA Warner          6567
3      KD Karthik          4843
4        MS Dhoni          5243
5       RG Sharma          6630
6      RV Uthappa          4954
7        S Dhawan          6769
8        SK Raina          5536
9         V Kohli          8014

In [68]:
trace=go.Bar(x=top10_scores['batter'],y=top10_scores['batsman_runs'])
data=[trace]
layout=go.Layout(title='Top Runs Scorer in Ipl',
                xaxis={'title':'batsman name'},
                yaxis={'title':'runs'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [9]:
wins_by_team = (
    matches["winner"]
    .value_counts()
    .reset_index()
    .rename(columns={"index": "team", "winner": "wins"})
    .head(10)
)

In [12]:
wins_by_team

                          wins  count
0               Mumbai Indians    144
1          Chennai Super Kings    138
2        Kolkata Knight Riders    131
3  Royal Challengers Bangalore    116
4             Rajasthan Royals    112
5              Kings XI Punjab     88
6          Sunrisers Hyderabad     88
7             Delhi Daredevils     67
8               Delhi Capitals     48
9              Deccan Chargers     29

In [18]:
iw=top10_df.groupby(['batter','inning'])['batsman_runs'].sum().reset_index()
mask=iw['inning']==1
mask1=iw['inning']==2
one=iw[mask]
two=iw[mask1]

one.rename(columns={'batsman_runs':'1st Innings'},inplace=True)
two.rename(columns={'batsman_runs':'2nd Innings'},inplace=True)

final=one.merge(two,on='batter')[['batter','1st Innings','2nd Innings']]
final

C:\Users\USER\AppData\Local\Temp\ipykernel_15876\169882119.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\USER\AppData\Local\Temp\ipykernel_15876\169882119.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

           batter  1st Innings  2nd Innings
0  AB de Villiers         3163         1999
1        CH Gayle         2873         2092
2       DA Warner         3280         3285
3      KD Karthik         2743         2099
4        MS Dhoni         3065         2178
5       RG Sharma         3600         3028
6      RV Uthappa         2120         2832
7        S Dhawan         3926         2843
8        SK Raina         3194         2334
9         V Kohli         4400         3604

In [ ]:
# overlay bar plot

In [20]:
trace1=go.Bar(x=final['batter'],y=final['1st Innings'],name='1st innings',
             marker={'color':'#00a65a'})
trace2=go.Bar(x=final['batter'],y=final['2nd Innings'],name='2nd Innings',
             marker={'color':'#a6a65a'})
data=[trace1,trace2]

layout=go.Layout(title='Inning wise Scores',
                xaxis={'title':'Batsman'},
                yaxis={'title':'Runs'},
                barmode='overlay')
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [22]:
trace1=go.Bar(x=final['batter'],y=final['1st Innings'],name='1st innings',
             marker={'color':'#00a65a'})
trace2=go.Bar(x=final['batter'],y=final['2nd Innings'],name='2nd Innings',
             marker={'color':'#a6a65a'})
data=[trace1,trace2]

layout=go.Layout(title='Inning wise Scores',
                xaxis={'title':'Batsman'},
                yaxis={'title':'Runs'},
                barmode='stack')
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [24]:
avg.head()

           batter        avg  batsman_runs
0  AB de Villiers  39.853846    148.580442
1      AD Russell  28.930233    164.224422
2        AJ Finch  24.904762    123.349057
3       AM Rahane  30.142857    120.321410
4       AT Rayudu  28.051613    124.584527

In [33]:
new_ipl=new_ipl[new_ipl['batsman_runs']==6]
six=new_ipl.groupby('batter')['batsman_runs'].count().reset_index()
x=avg.merge(six,on='batter')
trace=go.Scatter(x=x['avg'],y=['batsman_runs_x'],mode='markers',
                marker={'size':x['batsman_runs_y']})
data=[trace]
layout=go.Layout(title='Buble chart',
                xaxis={'title':'Average'},
                yaxis={'title':'SR'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [36]:
match_agg=deliveries.groupby(['match_id'])['total_runs'].sum().reset_index()
season_wise=match_agg.merge(matches,left_on='match_id',right_on='id')[['match_id','total_runs','season']]
season_wise

      match_id  total_runs   season
0       335982         304  2007/08
1       335983         447  2007/08
2       335984         261  2007/08
3       335985         331  2007/08
4       335986         222  2007/08
...        ...         ...      ...
1090   1426307         429     2024
1091   1426309         323     2024
1092   1426310         346     2024
1093   1426311         314     2024
1094   1426312         227     2024

[1095 rows x 3 columns]

In [41]:
trace=go.Box(x=season_wise[season_wise['season']==2017]['total_runs'],name='2017',marker={'color':'#00a65a'})
trace1=go.Box(x=season_wise[season_wise['season']==2008]['total_runs'],name='2008',)
data=[trace,trace1]
layout=go.Layout(title='Total Score Analysis',
                xaxis={'title':'Total_score'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'