In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("E:\data\data_set\Revenue_forcasting_CI.csv")

In [3]:
df

     Age  Marketing_Exposure  Previous_Purchases  Monthly_Revenue
0     58                   1                   1      2494.941406
1     48                   0                   9      2356.387522
2     34                   1                  11      1978.357376
3     27                   1                  16      3634.738976
4     40                   0                   7      2268.067368
..   ...                 ...                 ...              ...
195   41                   1                   5      2507.118415
196   30                   1                   6      2145.153525
197   35                   1                  19      3569.311825
198   52                   0                   8      2507.930324
199   28                   1                  16      3954.497832

[200 rows x 4 columns]

# population parameters (mean,std)

In [5]:
pop_mean=df['Monthly_Revenue'].mean()
pop_mean

np.float64(2664.6927557651634)

In [11]:
# variance population
deviation=df['Monthly_Revenue']-pop_mean

In [12]:
deviation

0      -169.751350
1      -308.305234
2      -686.335379
3       970.046220
4      -396.625387
          ...
195    -157.574340
196    -519.539231
197     904.619069
198    -156.762432
199    1289.805076
Name: Monthly_Revenue, Length: 200, dtype: float64

In [17]:
deviationsquare=deviation**2
deviationsquare=sum(deviationsquare)

In [18]:
variance=deviationsquare/df.shape[0]

In [19]:
variance

370205.51561214664

# standard deviation of population

In [20]:
std=np.sqrt(variance)
std

np.float64(608.4451623705678)

# sample of statestics(mean,std)

In [26]:
np.random.seed(42)
sample=df.sample(60)

In [27]:
sample

     Age  Marketing_Exposure  Previous_Purchases  Monthly_Revenue
95    28                   1                  18      3836.996695
15    41                   1                  16      3484.169727
30    22                   0                   8      2821.787011
158   46                   1                   9      2364.456730
128   49                   1                   4      1859.854436
115   45                   1                  18      4216.071263
69    40                   1                  15      3453.777816
170   22                   0                  13      3431.406783
174   21                   1                   5      1546.215989
45    26                   0                  19      2281.077588
66    33                   1                   5      3369.429993
182   21                   1                  10      2491.454796
165   51                   1                   3      1853.369942
78    44                   0                   1      2217.974371
186   51                   1                   7      2736.983165
177   56                   1                  11      2705.311026
56    48                   0                   8      2245.128448
152   46                   0                  17      3283.424532
82    20                   0                   4      2837.731624
68    59                   1                   5      2633.214768
124   51                   1                   4      2538.024020
16    21                   1                  14      3277.346397
148   44                   1                  17      3246.045190
93    47                   0                  17      2874.786365
65    27                   1                  19      3007.812154
60    29                   1                   7      2342.107078
84    43                   0                  10      2968.536260
67    42                   0                  14      2812.617676
125   58                   1                  18      3376.479988
132   34                   1                   9      1677.071620
9     30                   1                   7      2064.011573
18    49                   1                  19      2697.889106
55    23                   0                  16      3318.579232
75    48                   1                  16      2710.459885
150   52                   0                  13      2523.540348
104   59                   1                   1      2834.314242
135   32                   0                   3      1569.837487
137   26                   1                   4      2049.942171
164   51                   0                   5      1898.724441
76    34                   1                   7      2213.948117
79    26                   1                   5      2797.204644
197   35                   1                  19      3569.311825
38    44                   1                  15      2895.911023
24    41                   1                  10      3479.408317
122   45                   0                   9      2471.851334
195   41                   1                   5      2507.118415
29    34                   0                   1      1998.079441
19    57                   0                  15      3130.785921
143   47                   1                  17      2762.384103
86    36                   1                   1      2556.856400
114   24                   0                  19      1862.558749
173   21                   0                  14      3395.451748
5     58                   0                  10      3430.389027
126   51                   0                  13      2958.053327
117   58                   1                  17      3899.944338
73    45                   1                  12      2581.382234
140   21                   0                   7      2160.471177
98    53                   0                   1      2230.084501
172   36                   0                   7      3392.238615
96    27                   0                   3      1715.709031

In [31]:
sample_mean=sample['Monthly_Revenue'].mean()
sample_mean

np.float64(2724.451737112798)

# sample standard deviation

In [33]:
sample_devaition=sample['Monthly_Revenue']-sample_mean
sample_devaition

95     1112.544958
15      759.717990
30       97.335274
158    -359.995007
128    -864.597301
115    1491.619526
69      729.326079
170     706.955046
174   -1178.235748
45     -443.374149
66      644.978256
182    -232.996941
165    -871.081795
78     -506.477366
186      12.531427
177     -19.140711
56     -479.323289
152     558.972795
82      113.279887
68      -91.236969
124    -186.427717
16      552.894660
148     521.593453
93      150.334628
65      283.360417
60     -382.344659
84      244.084523
67       88.165939
125     652.028251
132   -1047.380117
9      -660.440164
18      -26.562631
55      594.127495
75      -13.991852
150    -200.911389
104     109.862505
135   -1154.614250
137    -674.509566
164    -825.727296
76     -510.503620
79       72.752907
197     844.860088
38      171.459286
24      754.956580
122    -252.600403
195    -217.333322
29     -726.372296
19      406.334184
143      37.932366
86     -167.595337
114    -861.892988
173     671.000011
5       705.937290
126     233.601590
117    1175.492601
73     -143.069503
140    -563.980560
98     -494.367236
172     667.786878
96    -1008.742706
Name: Monthly_Revenue, dtype: float64

In [35]:
squra_sampl_deviation=sum(sample_devaition**2)

In [37]:
sample_var=squra_sampl_deviation/sample.shape[0]
sample_var

382375.8026552312