# Avacado Prices datasets

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Creating Dataframes
- creating a list of dictionaries (construct row by row)

In [2]:
list_of_dicts=[
    {'name':'ginger','bred':'dachshund','height_cm':22,'weight_kg':10,'dob':'2019-03-14'},
    {'name':'scout','breed':'dalmatin','height_cm':59,'weight_kg':25,'dob':'2019-05-09'}
]
new_dogs=pd.DataFrame(list_of_dicts)
new_dogs

     name       bred  height_cm  weight_kg         dob     breed
0  ginger  dachshund         22         10  2019-03-14       NaN
1   scout        NaN         59         25  2019-05-09  dalmatin

* From a dictionary of lists (constructed column by column)

In [3]:
dict_of_lists = { 
     "name": ["Ginger", "Scout"], 
     "breed": ["Dachshund", "Dalmatian"], 
     "height_cm": [22, 59], 
     "weight_kg": [10, 25], 
     "date_of_birth": ["2019-03-14","2019-05-09"]  } 
new_dogs = pd.DataFrame(dict_of_lists) 
new_dogs

     name      breed  height_cm  weight_kg date_of_birth
0  Ginger  Dachshund         22         10    2019-03-14
1   Scout  Dalmatian         59         25    2019-05-09

<a id="Reading-and-writing-CSVs"></a>
# Reading and writing CSVs
* CSV = comma-separated values 
* Designed for DataFrame-like data 
* Most database and spreadsheet programs can use them or create them

In [4]:
df=pd.read_csv(r'E:\NIT_DAILYCLASS\classnots\11th - REGRESSION PROJECT\RESUME PROJECT -- PRICE PREDICTION\avocado.csv')

In [23]:
df.shape

(18249, 13)

In [5]:
df.head()

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

### Read CSV and assign index
<p>You can assign columns as index using "index_col" attribute.</p>
<p>Since I want to index Date there is another helpful function called "parse_date" which will parse the date in the rows such that we can perform more complex subsetting(eg monthly, weekly etc).</p>

In [6]:
df=pd.read_csv(r'E:\NIT_DAILYCLASS\classnots\11th - REGRESSION PROJECT\RESUME PROJECT -- PRICE PREDICTION\avocado.csv',
              parse_dates=True,index_col='Date')
df.head()

,Unnamed: 0,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
Date,,,,,,,,,,,,,
2015-12-27,0,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
2015-12-20,1,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2015-12-13,2,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
2015-12-06,3,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
2015-11-29,4,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

### Remove index from dataframe .reset_index(drop)

To reset the index use this function

In [7]:
df=df.reset_index(drop=True)
df.head()

,Unnamed: 0,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

# To write a CSV file function dataframe.to_csv(FILE_NAME)

In [8]:
avocado.to_csv("test_write.csv")

NameError: name 'avocado' is not defined

# Some useful pandas function

* **.head()** or **.head(x)** is used to get the first x rows of the DataFrame (x = 5 by default)

In [ ]:
df.head(1)

* **.tail()** or **.tail(x)** is used to get the last x rows of the DataFrame (x = 5 by default)

In [ ]:
df.tail(1)

* **.info()** is used to get a concise summary of the DataFrame

In [ ]:
df.info()

* **.shape** is used to get the dimensions of the DataFrame

In [ ]:
df.shape

* **.describe()** is used to view some basic statistical details like percentile, mean, std etc. of a DataFrame

In [ ]:
df.describe()

* **.values** this attribute return a Numpy representation of the given DataFrame

In [ ]:
df.values

* **.columns** this attribute return a Numpy representation of columns in the DataFrame

In [9]:
df.columns

Index(['Unnamed: 0', 'AveragePrice', 'Total Volume', '4046', '4225', '4770',
       'Total Bags', 'Small Bags', 'Large Bags', 'XLarge Bags', 'type', 'year',
       'region'],
      dtype='object')

<a id="Appending-Concatenating-Series"></a>
# Appending & Concatenating Series

append(): Series & DataFrame method
* Invocation:
* s1.append(s2)
* Stacks rows of s2 below s1 
<br>
<br>
<br>
concat(): pandas module function<br>
* Invocation:
* pd.concat([s1, s2, s3])
* Can stack row-wise or column-wise

In [10]:
even = pd.Series([2,4,6,8,10])
odd = pd.Series([1,3,5,7,9])

res = pd.concat([even,odd])
res

0     2
1     4
2     6
3     8
4    10
0     1
1     3
2     5
3     7
4     9
dtype: int64

### Observe index got messed up

You can use .reset_index(drop=True) to fix it<br>
Note: if drop = False then previous index will be added as a column

In [11]:
res.reset_index(drop=True)

0     2
1     4
2     6
3     8
4    10
5     1
6     3
7     5
8     7
9     9
dtype: int64


<a id="Sorting"></a>
# Sorting
syntax:<br>
> DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, kind=’quicksort’, na_position=’last’)

* by: Single/List of column names to sort Data Frame by.
* axis: 0 or ‘index’ for rows and 1 or ‘columns’ for Column.
* ascending: Boolean value which sorts Data frame in ascending order if True.
* inplace: Boolean value. Makes the changes in passed data frame itself if True.
* kind: String which can have three inputs(‘quicksort’, ‘mergesort’ or ‘heapsort’) of algorithm used to sort data frame.
* na_position: Takes two string input ‘last’ or ‘first’ to set position of Null values. Default is ‘last’.

In [12]:
df.sort_values(["AveragePrice", "year"], ascending=[True, False])

,Unnamed: 0,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
15261,43,0.44,64057.04,223.84,4748.88,0.00,59084.32,638.68,58445.64,0.00,organic,2017,CincinnatiDayton
7412,47,0.46,2200550.27,1200632.86,531226.65,18324.93,450365.83,113752.17,330583.10,6030.56,conventional,2017,PhoenixTucson
15473,43,0.48,50890.73,717.57,4138.84,0.00,46034.32,1385.06,44649.26,0.00,organic,2017,Detroit
15262,44,0.49,44024.03,252.79,4472.68,0.00,39298.56,600.00,38698.56,0.00,organic,2017,CincinnatiDayton
1716,0,0.49,1137707.43,738314.80,286858.37,11642.46,100891.80,70749.02,30142.78,0.00,conventional,2015,PhoenixTucson
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16720,18,3.04,12656.32,419.06,4851.90,145.09,7240.27,6960.97,279.30,0.00,organic,2017,RaleighGreensboro
16055,42,3.05,2068.26,1043.83,77.36,0.00,947.07,926.67,20.40,0.00,organic,2017,MiamiFtLauderdale
14124,7,3.12,19043.80,5898.49,10039.34,0.00,3105.97,3079.30,26.67,0.00,organic,2016,SanFrancisco
17428,37,3.17,3018.56,1255.55,82.31,0.00,1680.70,1542.22,138.48,0.00,organic,2017,Tampa
14125,8,3.25,16700.94,2325.93,11142.85,0.00,3232.16,3232.16,0.00,0.00,organic,2016,SanFrancisco

### Sorting by index

use df.sort_index(ascending=True/False)

<a id="Subsetting"></a>
# Subsetting

Subsetting is used to get a slice of the original dataframe

In [14]:
# Subsetting columns
df["AveragePrice"]

0        1.33
1        1.35
2        0.93
3        1.08
4        1.28
         ...
18244    1.63
18245    1.71
18246    1.87
18247    1.93
18248    1.62
Name: AveragePrice, Length: 18249, dtype: float64

In [17]:
df

,Unnamed: 0,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,7,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
18245,8,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
18246,9,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
18247,10,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
18248,11,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

### Subsetting multiple columns

In [18]:
# Subsetting multiple columns
df[["AveragePrice","Total Volume"]]

       AveragePrice  Total Volume
0              1.33      64236.62
1              1.35      54876.98
2              0.93     118220.22
3              1.08      78992.15
4              1.28      51039.60
...             ...           ...
18244          1.63      17074.83
18245          1.71      13888.04
18246          1.87      13766.76
18247          1.93      16205.22
18248          1.62      17489.58

[18249 rows x 2 columns]

### Subsetting rows

In [20]:
# Subsetting rows
df["AveragePrice"]<1

0        False
1        False
2         True
3        False
4        False
         ...
18244    False
18245    False
18246    False
18247    False
18248    False
Name: AveragePrice, Length: 18249, dtype: bool

- and then using it for subsetting the original dataframe

In [21]:
df[df["AveragePrice"]<1]

,Unnamed: 0,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
2,2,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
6,6,0.99,83453.76,1368.92,73672.72,93.26,8318.86,8196.81,122.05,0.0,conventional,2015,Albany
7,7,0.98,109428.33,703.75,101815.36,80.00,6829.22,6266.85,562.37,0.0,conventional,2015,Albany
13,13,0.99,106803.39,1204.88,99409.21,154.84,6034.46,5888.87,145.59,0.0,conventional,2015,Albany
43,43,0.99,55595.74,629.46,45633.34,181.49,9151.45,8986.06,165.39,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17169,43,0.99,155011.12,35367.23,5175.81,5.91,114462.17,95379.07,19083.10,0.0,organic,2017,SouthCentral
17170,44,0.99,171145.00,34520.03,6936.39,0.00,129688.58,117252.31,12436.27,0.0,organic,2017,SouthCentral
17536,39,0.98,402676.23,34093.33,58330.53,207.85,310044.52,155701.41,154343.11,0.0,organic,2017,West
17537,40,0.90,456645.91,36169.35,51398.72,139.55,368938.29,152159.53,216778.76,0.0,organic,2017,West
17540,43,0.99,367519.17,61166.48,55123.99,126.80,251101.90,112844.19,138257.71,0.0,organic,2017,West

### Subsetting based on text data

In [22]:
df[df['type']=='organic']

,Unnamed: 0,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
9126,0,1.83,989.55,8.16,88.59,0.00,892.80,892.80,0.00,0.0,organic,2015,Albany
9127,1,1.89,1163.03,30.24,172.14,0.00,960.65,960.65,0.00,0.0,organic,2015,Albany
9128,2,1.85,995.96,10.44,178.70,0.00,806.82,806.82,0.00,0.0,organic,2015,Albany
9129,3,1.84,1158.42,90.29,104.18,0.00,963.95,948.52,15.43,0.0,organic,2015,Albany
9130,4,1.94,831.69,0.00,94.73,0.00,736.96,736.96,0.00,0.0,organic,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,7,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
18245,8,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
18246,9,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
18247,10,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
18248,11,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

### Subsetting based on multiple conditions
You can use the logical operators to define a complex condition<br>
* "&" and
* "|" or
* "~" not

> ** SEPERATE EACH CONDITION WITH PARENTHESES TO AVOID ERRORS**

In [25]:
df[(df['AveragePrice']>3) & (df['type']=='organic')]

,Unnamed: 0,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
13037,12,3.03,3714.71,296.71,2699.80,0.00,718.20,718.20,0.00,0.0,organic,2016,LasVegas
14124,7,3.12,19043.80,5898.49,10039.34,0.00,3105.97,3079.30,26.67,0.0,organic,2016,SanFrancisco
14125,8,3.25,16700.94,2325.93,11142.85,0.00,3232.16,3232.16,0.00,0.0,organic,2016,SanFrancisco
16055,42,3.05,2068.26,1043.83,77.36,0.00,947.07,926.67,20.40,0.0,organic,2017,MiamiFtLauderdale
16720,18,3.04,12656.32,419.06,4851.90,145.09,7240.27,6960.97,279.30,0.0,organic,2017,RaleighGreensboro
17428,37,3.17,3018.56,1255.55,82.31,0.00,1680.70,1542.22,138.48,0.0,organic,2017,Tampa